### ISSUE TITLE
Feedback from Team ihatequarantine (kli00, dleung00, jshaw00, awan00)

### ISSUE THREAD

**Issue by pollsmor** [grace-mao23/P04_Mykolyangelo#2]
To Team Mykolyangelo:

- Not exactly ddoc based but the README is missing the breakdown of roles
- Tammy's name should be second from left (not sure how strict Mr. Mykolyk is about this)
- May want to specifically highlight the fact that Grace is your PM (since it's not in the role breakdown section)
- Bolding + all caps is pretty good for delineating sections, very neatly organized
- Hmm, does JS count as frontend or backend? (not anything wrong, legit don't have a clear cut answer)
- Very detailed component map
- Our team didn't think about listing out development stages, nice.
    - Would be nice to estimate by what date each stage should be finished by - a deadline is very helpful for Stuy students.
- Good justification for choice of database technologies

**Comment by tofr** [comment]
since we're not using node.js, etc. back-end apparatus, any of your JS will count as frontend
